name: daos_server
access_points: ['elster-storage']
#control_metadata:
#  path: /mnt/daos-metadata
provider: ucx+tcp

control_log_file: /tmp/daos_server.log
transport_config:
  allow_insecure: true
  #client_cert_dir: /etc/daos/certs/clients
  #ca_cert: /etc/daos/certs/daosCA.crt
  #cert: /etc/daos/certs/server.crt
  #key: /etc/daos/certs/server.key

telemetry_port: 9191
engines:
  -
    pinned_numa_node: 0
    targets: 4
    nr_xs_helpers: 1
    fabric_iface: eno1
    fabric_iface_port: 31416
    log_file: /tmp/daos_engine.0.log
    log_mask: ERR
    env_vars:
      - FI_SOCKETS_MAX_CONN_RETRY=1
      - FI_SOCKETS_CONN_TIMEOUT=2000
      - NA_PLUGIN_PATH=/usr/lib64/mercury/
      - UCX_TCP_PORT_RANGE=40000-45000
      - UCX_TCP_CM_REUSEADDR=y

    storage:
      -
        class: ram
        scm_mount: /mnt/daos
      -
        class: nvme
        bdev_list: [0000:07:00.0]
          #        bdev_roles:
          #          - data
          #          - meta
          #          - wal

    acceleration:
       engine: spdk
